### ISSUE TITLE
Функция CreateTopRouter

### ISSUE THREAD

**Issue by v-pereskokov** [frontend-park-mail-ru/2017_2_ToP#37]
- [x] Сделать функцию создания роутера и регистрирования компонент

- [x] Убрать константы, сразу засунуть объекты в функцию. Так не оч смотрится код

- [x] Убрать window.. внутри create. Но не копипастом туда. Сделать доп функцию и тд. Простыня не нужна. И тогда останется просто функция createtoprouter. Не надо будет ничего больше делать

**Comment by couatl** [comment]
Я сделяль
